"""add allowed_labels to campaigns

Revision ID: 05207e32c7ab
Revises: e055146d3c13
Create Date: 2026-07-27 23:59:03.330068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05207e32c7ab'
down_revision: Union[str, Sequence[str], None] = 'e055146d3c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('allowed_labels', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'allowed_labels')
    # ### end Alembic commands ###
